spring:
  config:
    import: optional:nacos:user-service.yaml
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848

server:
  port: 8081

management:
  tracing:
    sampling:
      probability: 1.0

mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.example.common.entity
  global-config:
    db-config:
      id-type: auto

seata:
  enabled: true
  service:
    vgroup-mapping:
      my_test_tx_group: default
  tx-service-group: my_test_tx_group
